#!/bin/bash

factorize() {
    number=$1
    for ((i = 2; i <= number / 2; i++)); do
        if [ $(($number % $i)) -eq 0 ]; then
            echo "$number=$i*$(($number / $i))"
            return
        fi
    done
    echo "$number=$number*1" # If the number is prime, factorization is the number * 1
}

main() {
    if [ $# -ne 1 ]; then
        echo "Usage: $0 <file>"
        return
    fi

    file_path=$1

    if [ ! -f $file_path ]; then
        echo "File '$file_path' not found."
        return
    fi

    while read -r line; do
        number=$(echo "$line" | tr -d '\n\r')
        factorize $number
    done < $file_path
}

main "$@"
